source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Placemat_Tests', :exclusive => true do
  pod "Placemat", :path => "../"

  pod 'Quick', '~> 0.4'
  pod 'Nimble', '2.0.0-rc.1'
end
