use_frameworks!

target 'Placemat_Example' do
  pod 'Placemat', path: '../'

  target 'Placemat_Tests' do
    inherit! :search_paths

    pod 'Nimble'
    pod 'Quick'
  end
end

post_install do |installer|
  installer.pods_project.targets.each  do |target|
      target.build_configurations.each  do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
   end
end
